package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Condition;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class NetcrackerTests extends TestBase {
    @Test
    @Description("TC001")
    @DisplayName("Check content on the page")
    void generatedTest() {
        step("Open https://www.netcracker.com", () -> {
            open("https://www.netcracker.com/");
        });

        step("Check primary-title", () -> {
            $(".homepage").shouldHave(Condition.text("Delivering the Digital Future"));
        });

        step("Click button Read more", () -> {
            $(".button-wrapper").click();
        });
        step("Click button Read more", () -> {
            $(".desktop").shouldHave(Condition.text("Netcracker Digital Platform"));
        });
    }

    @Test
    @Description("TC002")
    @DisplayName("Check open position")
    void search() {
        step("Open Netcracker Digital Platform page", () -> {
            open("https://www.netcracker.com/");
        });

        step("click on the open position", () -> {
            $(".btn-group").click();
        });

        step("click all departments", () -> {
            $(".filter-option pull-left").click();
        });
        step("select qa", () -> {
            $(".dropdown-menu inner").scrollTo().click();
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.netcracker.com'", () ->
            open("https://www.netcracker.com"));

        step("Page title should have text 'Netcracker - Home'", () -> {
            String expectedTitle = "Netcracker - Home";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.netcracker.com'", () ->
            open("https://www.netcracker.com"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}