package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Condition;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class NetcrackerTests extends TestBase {
    @Test
    @Description("TC001")
    @DisplayName("Check content on the page")
    void generatedTest() {
        step("Open https://www.netcracker.com", () -> {
            open("https://www.netcracker.com/");
        });

        step("Check primary-title", () -> {
            $(".homepage").shouldHave(Condition.text("Delivering the Digital Future"));
        });

        step("Click button Read more", () -> {
            $(".button-wrapper").click();
        });
        step("Check topic Netcracker Digital Platform", () -> {
            $(".desktop").shouldHave(Condition.text("Netcracker Digital Platform"));
        });
    }

    @Test
    @Description("TC002")
    @DisplayName("Check open position")
    void filter() {
        step("Open open-positions page", () -> {
            open("https://www.netcracker.com/careers/open-positions/");
        });

        step("click on banner", () -> {
            $(".gdpr-banner").$("#accept-gdrp").click();
        });

        step("click on keyword", () -> {
            $("#keyword").click();
        });

        step("set value", () -> {
            $("#keyword").setValue("qa");
        });
        step("check results", () -> {
            $("#positionslist").shouldHave(Condition.text("QA"));
        });

    }

    @Test
    @Description("TC003")
    @DisplayName("Check QA Analyst position")
    void checkQAAnalystPosition() {
        step("Open open-positions page", () -> {
            open("https://www.netcracker.com/careers/open-positions/");
        });

        step("click on banner", () -> {
            $(".gdpr-banner").$("#accept-gdrp").click();
        });

        step("click on keyword", () -> {
            $("#keyword").click();
        });

        step("set value", () -> {
            $("#keyword").setValue("qa");
        });
        step("check results", () -> {
            $("#positionslist").shouldHave(Condition.text("QA"));
        });

        step("click on QA Analyst", () -> {
            $("a[href='2594420.html']").scrollIntoView(true).click();
        });
        step("check Apply for this job", () -> {
            $("#form_for_cv").shouldHave(Condition.text("Apply for this job"));
        });

    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.netcracker.com'", () ->
            open("https://www.netcracker.com"));

        step("Page title should have text 'Netcracker - Home'", () -> {
            String expectedTitle = "Netcracker - Home";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    /*@Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.netcracker.com'", () ->
            open("https://www.netcracker.com"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }*/
}